### ISSUE TITLE
[JOSS-REVIEW] Installation instructions

### ISSUE THREAD

**Issue by kbevers** [laempy/pyoints#2]
In relation to https://github.com/openjournals/joss-reviews/issues/990

The installation instructions are only written for Ubuntu, although in the text it is somewhat hinted that Windows is also supported.

A clear description of which systems this package is intended for would be nice. Since this is a Python package it (theoretically) should work on at least Linux, OS X and Windows.

I recommend adding a conda environment file and basing the installation instructions on that instead. This will improve the chances of a successful installation immensely.

As a side note, I happen to work on a Mac and am having issues getting started with the installation. This package is not at fault, a mix of homebrew several GDAL and Python installations are complicating things a bit here. This could be avoided with a conda setup.

**Comment by laempy** [comment]
@kbevers thank you very much for the suggestion.

A conda recipe has been added and packages have been uploaded to https://anaconda.org/laempy/pyoints. The installation instructions in README.md have been updated accordingly. 

Since I have used conda for the first time and some pypi packages were not installed properly, it took a while to build a working recipe. Unfortunately I was not able to cross-compile a osx package. So currently only win-64 and linux-64 packages have been uploaded. I hope the recipe also works for osx.

**Comment by kbevers** [comment]
The conda recipe didn't work for me on OS X. I have not tried to figure out a way to fix it since I managed to get a working install setup by installing the needed packages with `conda install` and `pip install`, depending on the package. Finally a `pip install -e .` in the source directory installed the package.
